### ISSUE TITLE
更改拼音的标签进行分类

### ISSUE THREAD

**Issue by zw76859420** [letiantian/Pinyin2Hanzi#4]
感谢朋友您分享你的研究成果；
针对您提出的拼音合理问题，我想提出一个问题，比如说“学”在中文里面的拼音是“xue2”（其中2代表的是声调），如果按照您做的应该是“xve”，这样的标签无法明确显示标签的声调，能否做一个以字母为声调的拼音建模方式，实现拼音到汉字的转换！
我的QQ：76859420 
欢迎朋友加我QQ，一起讨论一些具体问题！

**Comment by letiantian** [comment]
无支持声调的计划，可以自行实现。
