### ISSUE TITLE
请问HMM和DAG出的分数有什么不同？

### ISSUE THREAD

**Issue by aluminumbox** [letiantian/Pinyin2Hanzi#6]
由拼音生成字的过程中，使用了HMM模型，并对生成的字进行了打分。
然后又使用了DAG对字重新打分。请问这两个分数有什么不同呢？不是很理解这个重新打分的意义？训练的语言模型体现在哪一部分了呢？
谢谢！

**Comment by letiantian** [comment]
是不同的打分方式，不要混在一起看
